# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'
source 'https://cdn.cocoapods.org/'

# Define the main target for the iOS app
target 'ApproovShapes' do
  use_frameworks!
  platform :ios, '12.0'
  # Use the local Podspec for the ApproovURLSession
  pod 'ApproovURLSession', '~> 3.5.1'
  
end

# Define the target for the watchOS app
target 'ShapesWatchApp Watch App' do
  use_frameworks!
  platform :watchos, '7.0'
  # Use the local Podspec for the ApproovURLSession
  pod 'ApproovURLSession',  '~> 3.5.1'

end
